### ISSUE TITLE
run: python setup.py gcc ERROR

### ISSUE THREAD

**Issue by yangluoshen** [xupingmao/subpy#5]
执行python setup.py gcc报了错，错误信息如下
```
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    main()
  File "setup.py", line 100, in main
    buildOne(cc)
  File "setup.py", line 89, in buildOne
    build(ccompiler, libs)
  File "setup.py", line 29, in build
    dstMtime = mtime(dstPath)
  File "/home/yangluo/github/subpy/src/boot.py", line 98, in mtime
    return os.path.getmtime(fname)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'bin.c'
```
定位了下 bin.c 的使用位置:
```
yangluo@yangluoPC:~/github/subpy/src$ grep -rwn 'bin.c' .
./setup.py:13:def build(cc="tcc", libs=None, dstPath = "bin.c"):
./setup.py:55:        #remove("../bin.c")
./tags:420:build	setup.py	/^def build(cc="tcc", libs=None, dstPath = "bin.c"):$/;“
./vm.c:14:#include "bin.c"
```
应该是默认参数吧，但是好像找不到这个文件（bin.c）
```
yangluo@yangluoPC:~/github/subpy/src$ sudo find / -name 'bin.c'
yangluo@yangluoPC:~/github/subpy/src$ 
```
是不是漏了？

**Comment by xupingmao** [comment]
bin.c是编译器生成的，setup.py有一个BUG，已经修复
